# Generated by Django 4.0.8 on 2022-11-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0044_appointment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_information',
            name='department',
            field=models.CharField(blank=True, choices=[('De-addiction', 'De-addiction'), ('Pulmonology', 'Pulmonology'), ('Physiatrists', 'Physiatrists')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor_information',
            name='register_status',
            field=models.CharField(blank=True, default='Pending', max_length=200, null=True),
        ),
    ]
